/**
 * Migrations.
 *
 * Migrations are hand-written SQL in TypeScript files under src/db/migrations/. Nothing is
 * generated by diffing a declared schema against the database. That is slower to write and it
 * means every statement applied to your database is a statement you decided on.
 *
 * The migration ledger lives in the application's own schema, so it is dropped and recreated
 * with the rest of the application's data and can never be confused with another project's.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { sql } from 'kysely';
import { FileMigrationProvider, Migrator, type MigrationInfo } from 'kysely/migration';
import type { AppDatabase } from './index.js';

export const MIGRATION_TABLE = 'kysely_migration';
export const MIGRATION_LOCK_TABLE = 'kysely_migration_lock';

/** Absolute path to the migration folder, correct under both tsx (src/) and node (dist/). */
export function migrationFolder(): string {
  return path.join(import.meta.dirname, 'migrations');
}

/**
 * Create the application schema if it does not exist.
 *
 * This runs before the migrator, because the migration ledger table itself lives inside the
 * schema. It is the only DDL in the application that is not a migration, and it is safe to
 * repeat.
 *
 * The schema name is interpolated rather than parameterised — PostgreSQL does not accept a
 * bind parameter in a DDL identifier position. That is why src/config validates DB_SCHEMA
 * against /^[a-z_][a-z0-9_]{0,62}$/ before it ever reaches this line.
 */
export async function ensureSchema(db: AppDatabase, schema: string): Promise<void> {
  if (!/^[a-z_][a-z0-9_]{0,62}$/.test(schema)) {
    throw new Error(`Refusing to create schema with unsafe name "${schema}"`);
  }
  await sql.raw(`create schema if not exists "${schema}"`).execute(db);
}

export function createMigrator(db: AppDatabase, schema: string): Migrator {
  return new Migrator({
    db,
    provider: new FileMigrationProvider({
      fs,
      path,
      migrationFolder: migrationFolder(),
      // Import via a file:// URL. Node's ESM loader accepts absolute POSIX paths, but a URL
      // is unambiguous and does not depend on that behaviour.
      import: (filePath: string) => import(pathToFileURL(filePath).href),
    }),
    migrationTableName: MIGRATION_TABLE,
    migrationLockTableName: MIGRATION_LOCK_TABLE,
    migrationTableSchema: schema,
    // Strict ordering. A migration that appears with a name alphabetically earlier than an
    // already-applied one is an error, not something to quietly interleave — that situation
    // means two branches created migrations concurrently and a human needs to decide.
    allowUnorderedMigrations: false,
  });
}

export interface MigrationStatus {
  /** Names of migrations recorded as applied, in order. */
  applied: string[];
  /** Names of migrations present on disk but not yet applied, in order. */
  pending: string[];
  total: number;
  isUpToDate: boolean;
  /** When the most recent migration was applied, if any. */
  lastAppliedAt: Date | null;
}

/**
 * Report the migration state without changing it.
 *
 * Read-only by construction: Kysely's `getMigrations()` checks whether the ledger table exists
 * and returns an empty applied-list if it does not, rather than creating it. That matters
 * because this same function backs `GET /ready`, and a readiness probe must never mutate the
 * thing it is inspecting.
 */
export async function getMigrationStatus(
  db: AppDatabase,
  schema: string,
): Promise<MigrationStatus> {
  const migrator = createMigrator(db, schema);
  const migrations: readonly MigrationInfo[] = await migrator.getMigrations();

  const applied = migrations.filter((m) => m.executedAt !== undefined);
  const pending = migrations.filter((m) => m.executedAt === undefined);
  const timestamps = applied
    .map((m) => m.executedAt)
    .filter((d): d is Date => d instanceof Date)
    .sort((a, b) => a.getTime() - b.getTime());

  return {
    applied: applied.map((m) => m.name),
    pending: pending.map((m) => m.name),
    total: migrations.length,
    isUpToDate: pending.length === 0 && migrations.length > 0,
    lastAppliedAt: timestamps.at(-1) ?? null,
  };
}

export interface MigrationRunResult {
  applied: string[];
  failed: string[];
  error: unknown;
}

/** Apply every pending migration. Kysely takes an advisory lock, so concurrent runners queue. */
export async function migrateToLatest(
  db: AppDatabase,
  schema: string,
): Promise<MigrationRunResult> {
  await ensureSchema(db, schema);
  const { error, results } = await createMigrator(db, schema).migrateToLatest();
  return {
    applied: (results ?? []).filter((r) => r.status === 'Success').map((r) => r.migrationName),
    failed: (results ?? []).filter((r) => r.status === 'Error').map((r) => r.migrationName),
    error,
  };
}

/** Roll back exactly one migration. */
export async function migrateDownOne(db: AppDatabase, schema: string): Promise<MigrationRunResult> {
  const { error, results } = await createMigrator(db, schema).migrateDown();
  return {
    applied: (results ?? []).filter((r) => r.status === 'Success').map((r) => r.migrationName),
    failed: (results ?? []).filter((r) => r.status === 'Error').map((r) => r.migrationName),
    error,
  };
}

/**
 * Drop the application schema and recreate it empty.
 *
 * Scoped by construction: `DROP SCHEMA "acme" CASCADE` cannot reach an object outside that
 * schema. Compare with truncating a hand-maintained list of table names, where the safety of
 * the operation depends on the list being complete and current.
 *
 * Callers MUST have already passed src/db/guard.ts. This function does not check intent —
 * keeping the check in one place means it cannot be half-applied.
 */
export async function dropAndRecreateSchema(db: AppDatabase, schema: string): Promise<void> {
  if (!/^[a-z_][a-z0-9_]{0,62}$/.test(schema)) {
    throw new Error(`Refusing to drop schema with unsafe name "${schema}"`);
  }
  await sql.raw(`drop schema if exists "${schema}" cascade`).execute(db);
  await sql.raw(`create schema "${schema}"`).execute(db);
}
