#!/usr/bin/env bash
#
# Local development PostgreSQL — a disposable container on YOUR machine.
#
#   ./scripts/dev-postgres.sh          create (or report) the container, role, and databases
#   ./scripts/dev-postgres.sh --down   stop and remove the container and its data
#   ./scripts/dev-postgres.sh --psql   open an interactive psql session as the app role
#
# ---------------------------------------------------------------------------
# WHAT THIS IS NOT
# ---------------------------------------------------------------------------
# This is a local development convenience and nothing else.
#
#   - It is NOT part of the deployment path. The Dockerfile does not reference it and
#     docs/UNRAID_DEPLOYMENT.md does not use it.
#   - It does NOT touch your Unraid server. Acme Commerce never creates or manages a
#     PostgreSQL instance in any environment it is deployed to; it connects to one that
#     already exists.
#   - There is no Docker Compose file, here or anywhere in this project.
#
# The SQL it runs is deliberately the same SQL documented in docs/POSTGRES_SETUP.md for your
# real PostgreSQL server. Running it here means the privilege model you develop against is the
# privilege model you deploy against — in particular, the application role is NOT a superuser.
#
# Idempotent: safe to re-run. Generated passwords are stored in .dev-postgres.env (gitignored)
# so a second run can reprint them rather than locking you out of your own container.

set -euo pipefail

CONTAINER_NAME="${ACME_DEV_PG_CONTAINER:-acme-pg-dev}"
HOST_PORT="${ACME_DEV_PG_PORT:-55432}"
PG_IMAGE="${ACME_DEV_PG_IMAGE:-postgres:17-alpine}"
APP_ROLE="${ACME_DEV_APP_ROLE:-acme_app}"
DEV_DB="acme_commerce_dev"
TEST_DB="acme_commerce_test"
CREDENTIALS_FILE=".dev-postgres.env"

bold=$(printf '\033[1m'); green=$(printf '\033[32m'); yellow=$(printf '\033[33m'); dim=$(printf '\033[2m'); reset=$(printf '\033[0m')
say()  { printf '%s%s%s\n' "$bold" "$1" "$reset"; }
ok()   { printf '  %s✓%s %s\n' "$green" "$reset" "$1"; }
note() { printf '  %s%s%s\n' "$dim" "$1" "$reset"; }
warn() { printf '  %s!%s %s\n' "$yellow" "$reset" "$1"; }
die()  { printf '\n%s\n\n' "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die 'docker is not on PATH. Install Docker Desktop (or the Docker engine) and try again.'
docker info >/dev/null 2>&1 || die 'The Docker daemon is not responding. Start Docker and try again.'

# ---------------------------------------------------------------------------
# --down
# ---------------------------------------------------------------------------
if [[ "${1:-}" == '--down' ]]; then
  say "Removing the local development PostgreSQL container"
  if docker inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
    docker rm -f "$CONTAINER_NAME" >/dev/null
    ok "Removed container $CONTAINER_NAME (its data volume is anonymous and goes with it)"
  else
    note "No container named $CONTAINER_NAME exists; nothing to do."
  fi
  note "$CREDENTIALS_FILE is left in place. Delete it if you want fresh passwords next time."
  exit 0
fi

# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------
if [[ -f "$CREDENTIALS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CREDENTIALS_FILE"
  REUSED_CREDENTIALS=1
else
  ACME_DEV_PG_SUPERUSER_PASSWORD="$(openssl rand -hex 16)"
  ACME_DEV_APP_PASSWORD="$(openssl rand -hex 16)"
  cat > "$CREDENTIALS_FILE" <<CREDS
# Generated by scripts/dev-postgres.sh. Gitignored. LOCAL DEVELOPMENT ONLY.
# These credentials belong to a throwaway container on this machine. They are not, and must
# never become, the credentials of any real PostgreSQL server.
ACME_DEV_PG_SUPERUSER_PASSWORD=$ACME_DEV_PG_SUPERUSER_PASSWORD
ACME_DEV_APP_PASSWORD=$ACME_DEV_APP_PASSWORD
CREDS
  chmod 600 "$CREDENTIALS_FILE"
  REUSED_CREDENTIALS=0
fi

say "Local development PostgreSQL"
note "container $CONTAINER_NAME   image $PG_IMAGE   host port $HOST_PORT"
[[ $REUSED_CREDENTIALS -eq 1 ]] && note "reusing credentials from $CREDENTIALS_FILE"

# ---------------------------------------------------------------------------
# Container
# ---------------------------------------------------------------------------
if docker inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
  state="$(docker inspect -f '{{.State.Status}}' "$CONTAINER_NAME")"
  if [[ "$state" == 'running' ]]; then
    ok "Container is already running"
  else
    docker start "$CONTAINER_NAME" >/dev/null
    ok "Started the existing container (was $state)"
  fi
else
  docker pull "$PG_IMAGE" >/dev/null 2>&1 || true
  docker run -d \
    --name "$CONTAINER_NAME" \
    -e POSTGRES_PASSWORD="$ACME_DEV_PG_SUPERUSER_PASSWORD" \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=postgres \
    -p "${HOST_PORT}:5432" \
    "$PG_IMAGE" >/dev/null
  ok "Created container $CONTAINER_NAME"
fi

# A container that is "running" is not necessarily accepting connections yet.
printf '  waiting for PostgreSQL to accept connections'
for _ in $(seq 1 40); do
  if docker exec "$CONTAINER_NAME" pg_isready -U postgres -q 2>/dev/null; then
    printf '\r'; ok "PostgreSQL is accepting connections            "
    break
  fi
  printf '.'; sleep 0.5
done
docker exec "$CONTAINER_NAME" pg_isready -U postgres -q 2>/dev/null \
  || die "PostgreSQL did not become ready. Inspect it with: docker logs $CONTAINER_NAME"

SERVER_VERSION="$(docker exec "$CONTAINER_NAME" psql -U postgres -tAc 'show server_version;' | tr -d '[:space:]')"
note "server version $SERVER_VERSION"

# ---------------------------------------------------------------------------
# Role and databases — the same SQL as docs/POSTGRES_SETUP.md
# ---------------------------------------------------------------------------
# The application role is NOT a superuser. It owns its two databases, which under PostgreSQL
# 15+ makes it the effective owner of each database's `public` schema via pg_database_owner.
# That is enough to create the `acme` schema and everything in it, and no more.
docker exec -i "$CONTAINER_NAME" psql -U postgres -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN
    CREATE ROLE ${APP_ROLE} WITH LOGIN PASSWORD '${ACME_DEV_APP_PASSWORD}';
  ELSE
    -- Re-assert the password so a reused container and a regenerated credentials file cannot
    -- drift apart and leave you unable to authenticate.
    ALTER ROLE ${APP_ROLE} WITH LOGIN PASSWORD '${ACME_DEV_APP_PASSWORD}';
  END IF;
END
\$\$;
SQL
ok "Role ${APP_ROLE} exists with the password in $CREDENTIALS_FILE"

# CREATE DATABASE cannot run inside a transaction or a DO block, so existence is checked first.
for db in "$DEV_DB" "$TEST_DB"; do
  exists="$(docker exec "$CONTAINER_NAME" psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${db}';" | tr -d '[:space:]')"
  if [[ "$exists" == '1' ]]; then
    ok "Database ${db} already exists"
  else
    docker exec "$CONTAINER_NAME" psql -U postgres -q -c "CREATE DATABASE ${db} OWNER ${APP_ROLE} ENCODING 'UTF8';"
    ok "Created database ${db} owned by ${APP_ROLE}"
  fi
done

# Prove the app role can actually log in and create objects. Discovering a privilege problem
# here is far cheaper than discovering it from a failed migration.
docker exec "$CONTAINER_NAME" env PGPASSWORD="$ACME_DEV_APP_PASSWORD" \
  psql -U "$APP_ROLE" -d "$DEV_DB" -h 127.0.0.1 -tAc \
  'CREATE SCHEMA IF NOT EXISTS _privilege_probe; DROP SCHEMA _privilege_probe;' >/dev/null \
  || die "Role ${APP_ROLE} cannot create a schema in ${DEV_DB}. Check the database owner."
ok "Role ${APP_ROLE} can create schemas in ${DEV_DB} without superuser rights"

# ---------------------------------------------------------------------------
# --psql
# ---------------------------------------------------------------------------
if [[ "${1:-}" == '--psql' ]]; then
  printf '\n'
  say "Opening psql as ${APP_ROLE} on ${DEV_DB}"
  note "Try: \\dn   \\dt acme.*   select count(*) from acme.products;"
  exec docker exec -it "$CONTAINER_NAME" env PGPASSWORD="$ACME_DEV_APP_PASSWORD" \
    psql -U "$APP_ROLE" -d "$DEV_DB" -h 127.0.0.1
fi

# ---------------------------------------------------------------------------
# What to do next
# ---------------------------------------------------------------------------
DEV_URL="postgres://${APP_ROLE}:${ACME_DEV_APP_PASSWORD}@127.0.0.1:${HOST_PORT}/${DEV_DB}"
TEST_URL="postgres://${APP_ROLE}:${ACME_DEV_APP_PASSWORD}@127.0.0.1:${HOST_PORT}/${TEST_DB}"

printf '\n'
say 'Add these to your .env  (cp .env.example .env  if you have not already)'
printf '\n'
printf 'DATABASE_URL=%s\n' "$DEV_URL"
printf 'TEST_DATABASE_URL=%s\n' "$TEST_URL"
printf 'DB_SSL=disable\n'
printf '\n'

if [[ ! -f .env ]]; then
  warn 'No .env found. Creating one from .env.example with these values filled in.'
  cp .env.example .env
  # macOS and GNU sed disagree about -i, so the file is rewritten rather than edited in place.
  python3 - "$DEV_URL" "$TEST_URL" <<'PY'
import re, sys
dev, test = sys.argv[1], sys.argv[2]
s = open('.env').read()
s = re.sub(r'^DATABASE_URL=.*$', f'DATABASE_URL={dev}', s, flags=re.M)
s = re.sub(r'^TEST_DATABASE_URL=.*$', f'TEST_DATABASE_URL={test}', s, flags=re.M)
s = re.sub(r'^HOST=.*$', 'HOST=127.0.0.1', s, flags=re.M)
open('.env', 'w').write(s)
PY
  ok 'Wrote .env (gitignored)'
fi

say 'Then'
note 'npm run migrate:up      apply migrations'
note 'npm run db:seed         load 20 products and 49 variants'
note 'npm run dev             start the API on http://127.0.0.1:3000'
note 'npm run smoke           exercise every endpoint from the command line'
printf '\n'
